---
- name: Install node and npm
  hosts: lightsail
  tasks: 
    - name: Update apt repo and cache
      apt: #update_cache=yes force_apt_get=yes cache_valid_time=3600
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
      become: yes  
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
      become: yes    

# - name: Create new linux user for node app 
#   hosts: lightsail
#   tasks:
#     - name: create linux user
#       user:
#         name: kamran
#         comment: kamran
#         group: ubuntu
#         register: user_creation_result
#     - debug: msg={{user_creation_result.id}}
#       become: yes      

- name: Deploy nodejs app
  hosts: lightsail
  become: true
  vars_files:
    - project-vars
  #become_user: kamran
  tasks: 
    - name: copy nodejs folder to a server
      copy:
        src: /home/kamran/Downloads/test.tgz
        dest: "{{destination}}"
    - name: unpack the nodejs file
      unarchive: 
        src: /home/ubuntu/test.tgz
        dest: "{{destination}}"
        remote_src: yes
      register: user_creation_result
    - debug: msg={{user_creation_result}}  
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}      
                    

