workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always  

stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
    - chmod +x prep-work.sh
    - ./prep-work.sh

  script:
    - echo "Running unit tests..."
  after_script:
    - echo "Cleaning up temporary data..."  
    - rm -r test-data-folder
    - ls

run_lint_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running lint tests..."
  after_script:
    - echo "Cleaning up temporary data..."  

build_image:
  only:
    - main
  stage: build
  script:
    - echo "Building the Docker image..."
    - echo "Tagging the image..."

push_image:
  only:
    - main
  stage: build
  needs:
    - build_image
  script:
    - echo "Logging the docker registory..."
    - echo "Pusing to docker registory..."

deploye_image:
  only:
    - main
  stage: deploy
  script:
    - echo "Deploying the docker registory..."
